config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'poncetsas', to: 'pages#poncetsas'
  get 'aze', to: 'pages#aze'
  get 'lfelec', to: 'pages#lfelec'
  get 'mattard', to: 'pages#mattard'

  get 'deniaux_couverture', to: 'pages#deniaux_couverture'
  get 'rl', to: 'pages#rl'
  get 'peinture_picant', to: 'pages#peinture_picant'
  get 'profil_amenagement', to: 'pages#profil_amenagement'
  get 'benoist', to: 'pages#benoist'
  get 'logikinov', to: 'pages#logikinov'
  get 'normandie_chauffage', to: 'pages#normandie_chauffage'
  get 'samandco_tp', to: 'pages#samandco_tp'

  get 'mention', to: 'pages#mention'
  resources :contacts, only: [:new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :message, presence: true
  validates :name, presence: true
  validates :email,
      :presence => :true,
      :format => {
        :with => /\S+@\S+\.\S+/i,
        :message => "le format de l'adresse e-mail doit être correct."
      }
  validates :phone, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @contact = Contact.new()
  end

  def create
    @contact = Contact.new(contact_params)
    # "tout"=>"0",
    if @contact.tout
      # attention manque adresse Deniaux
      @contact.emails = ["contact@samandco-tp.com", "julien.nc14@gmail.com", "aze2j@live.fr", "poncetemilien@hotmail.fr", "f.lefortier@gmail.com", "stephmatt.carrelage@aliceadsl.fr", "benoit.briere@logikinov.com", "a.lefrancois@rlamenagement.com", "profil@profil-amenagement.com", "contact@benoist.fr", "romain.picant@orange.fr"]
      ContactMailer.information(@contact).deliver_now
    elsif
      if @contact.electricite
        @contact.emails << "f.lefortier@gmail.com"
      end
      if @contact.plombier
        @contact.emails << "poncetemilien@hotmail.fr"
      end
      if @contact.agencement
        @contact.emails << "profil@profil-amenagement.com"
      end
      if @contact.maconnerie
        @contact.emails << "aze2j@live.fr"
      end
      if @contact.cheminee
        @contact.emails << "contact@benoist.fr"
      end
      if @contact.peinture
        @contact.emails << "romain.picant@orange.fr"
      end
      if @contact.plaquiste
        @contact.emails << "a.lefrancois@rlamenagement.com"
      end
      if @contact.couverture
        #@contact.emails << "x"
      end
      if @contact.terrassement2
        @contact.emails << "contact@samandco-tp.com"
      end
      if @contact.carrelage
        @contact.emails << "stephmatt.carrelage@aliceadsl.fr"
      end
      if @contact.chauffagiste
        @contact.emails << "julien.nc14@gmail.com"
      end

      ContactMailer.information(@contact).deliver_now
    end
      redirect_to root_path
      flash[:notice] = "Votre message a bien été transmis"
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :address, :phone, :message, :tout, :plombier, :electricite, :peinture, :carrelage, :cheminee, :menuiserie, :couverture, :agencement, :plaquiste, :maconnerie, :terrassement2, :chauffagiste)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GA14</title>
    <meta name="description" content="Groupement d'artisans sur Caen">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico'%>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"
    />
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/sidebar' %>
    <%= render 'shared/modal' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/aze.html.erb
<div class="pageforeach">
  <img id="logo" src="../assets/aze_logo.png" alt="" >
  <br>
  <h1>Entreprise de maçonnerie et gros oeuvre à Caen, pour des travaux de construction et de rénovation.</h1><br>
  <h3>coordonnées</h3>
  <p>7 rue du Pont Rouge<br>14320 LAIZE LA VILLE</p>
  <p style="font-weight: bolder;">06 19 76 08 21 - aze2j@live.fr</p>
  <h2>Interventions</h2>
  <div class="domaines">
    <div class="domaine">
      <h5>Maçonnerie</h5>
    </div>
    <div class="domaine">
      <h5>Gros Oeuvre</h5>
    </div>
    <div class="domaine">
      <h5>Autres</h5>
    </div>
  </div>
  <br>
  <h2>Mes dernières réalisations</h2>
  <br>
  <h3>Rénovation d'un mur en pierre de Caen</h3>
  <div class="domaines">
    <img src="../assets/aze10.jpg" alt="">
    <img src="../assets/aze11.jpg" alt="">
    <img src="../assets/aze12.jpg" alt="">
  </div>
  <h3>Construction d'une piscine d'intérieur</h3>
  <div class="domaines">
    <img src="../assets/aze1.jpg" alt="">
    <img src="../assets/aze2.jpg" alt="">
    <img src="../assets/aze3.jpg" alt="">
  </div>
    <div class="domaines">
    <img src="../assets/aze4.jpg" alt="">
    <img src="../assets/aze5.jpg" alt="">
  </div>
  <h3>Construction d'une maison moderne</h3>
  <div class="domaines">
    <img src="../assets/aze6.jpg" alt="">
    <img src="../assets/aze7.jpg" alt="">
  </div>
  <h3>Rénovation et extension d'un garage</h3>
  <div class="domaines">
    <img src="../assets/aze8.jpg" alt="">
    <img src="../assets/aze9.jpg" alt="">
  </div>
</div>

app/views/pages/benoist.html.erb
<div class="pageforeach">
  <img id="logo" src="../assets/benoist.png" alt="" >
  <br>
  <h1>Distributeur et installateur des plus grandes marques de poêles à bois,<br>à granulés, inserts, cheminées bois, gaz, métalliques.</h1><br>
  <div style="display: flex;">
    <a href="https://www.benoist.fr/" class="button">visitez le site</a>
  </div>
  <h3>à retrouver dans 2 show-rooms :</h3>
  <p>14470 COURSEULLES SUR MER</p>
  <p>14120 MONDEVILLE - Parking Rochebobois</p>
  <p style="font-weight: bolder;">02 31 36 10 15 - contact@benoist.fr</p>
  <h2>Interventions</h2>
  <div class="domaines">
    <div class="domaine">
      <h5>Poëles à bois et à granulés</h5>
    </div>
    <div class="domaine">
      <h5>Inserts</h5>
    </div>
    <div class="domaine">
      <h5>Cheminées bois, gaz et métalliques</h5>
    </div>
  </div>
  <br>
  <h2>Nos dernières réalisations</h2>
  <br>
  <h3>Cheminées</h3>
  <div class="domaines">
    <img src="../assets/cheminee1.jpg" alt="">
    <img src="../assets/cheminee2.jpg" alt="">
    <img src="../assets/cheminee3.jpg" alt="">
  </div>
  <h3>Poëles</h3>
  <div class="domaines">
    <img src="../assets/poele1.jpg" alt="">
    <img src="../assets/poele2.jpg" alt="">
  </div>
</div>

app/views/pages/deniaux_couverture.html.erb
<div class="pageforeach">
  <!-- <img id="logo" src="../assets/lfelec.png" alt="" > -->
  <br>
  <h1>Entreprise du bâtiment spécialisée dans la couveture, charpente, terrasse bois, le bardage et l'isolation.</h1><br>
  <h3>coordonnées</h3>
  <p>11 impasse de la Teinture<br>14690 LE BÔ</p>
  <p style="font-weight: bolder;">02 31 09 47 36 - 06 16 38 59 51</p>
  <h2>Interventions</h2>
  <div class="domaines">
    <div class="domaine">
      <h5>Charpente</h5>
    </div>
    <div class="domaine">
      <h5>Couverture</h5>
    </div>
    <div class="domaine">
      <h5>Bardage</h5>
    </div>
    <div class="domaine">
      <h5>Isolation</h5>
    </div>
  </div>
  <br>
  <h2>Mes dernières réalisations</h2>
  <br>
  <h3>Retrouvez prochainement mes dernières réalisations</h3>
</div>

app/views/pages/home.html.erb
<div>
  <div class="home">
    <div id="nav" class="d-none" style="position: sticky; z-index: 2; top: 0px; background: rgb(180,174,165);background: linear-gradient(180deg, rgba(180,174,165,1) 6%, rgba(107,107,110,0) 100%); height: 12vh; width: 100%;">
      <div id="contact" class="d-none" style="position: sticky; top: 32px; margin-left: 85%; z-index: 2;">
        <img style="width:80px; margin-top: 16px; cursor: pointer;" src="../assets/contact-button2.png" data-toggle="modal" data-target="#exampleModal">
      </div>
    </div>
    <img style="display: block; margin: auto; width: 60vw;" src="../assets/logo_bis.png" alt="Groupement des Artisans du Calvados">
    <h1 class="subtitle_logo">GROUPEMENT DES ARTISANS DU CALVADOS</h1>
    <div class="resume">
      <p class="animate__animated animate__backInLeft resume-left"><strong>GA14, le Groupement des Artisans du Calvados</strong> a été créé grâce à la collaboration de professionnels spécialisés dans les différents domaine du BTP pour vous garantir un travail de qualité, le respect des délais et votre entière satisfaction.</p>
      <span style="display: flex; align-items: center; justify-content: center;">
       <p><strong>NOTRE AMBITION : faire de votre projet une réalité !</strong></p>
      </span>
      <p class="animate__animated animate__backInRight resume-right">De plus, les membres du <strong>GA14 sont des professionnels</strong> qui jouissent de plusieurs années d'expérience, des professionnels reconnus, certifiés dans le secteur du BTP, vous garantissant une qualité de travail et des prestations qui répondent à vos attentes et vos envies.</p>
    </div>
    <div class="realisation">
      <div class="blueline">
        <span style="border:2px solid #0f738a; width: 15%; height: 2px;"></span>
        <h3>Les dernières réalisations de nos artisans</h3>
        <span style="border:2px solid #0f738a; width: 15%; height: 2px;"></span>
      </div>
      <br>
      <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block" src="../assets/dressing.jpg">
          </div>
          <div class="carousel-item">
            <img class="d-block" src="../assets/cheminee1.jpg" >
          </div>
          <div class="carousel-item">
            <img class="d-block" src="../assets/baie.png">
          </div>
          <div class="carousel-item">
            <img class="d-block" src="../assets/aze12.jpg">
          </div>
          <div class="carousel-item">
            <img class="d-block" src="../assets/apres1.jpg">
          </div>
        </div>
      </div>
    </div>
    <br>
    <h3 style="margin-top: 32px; text-align: center">Retrouvez les membres du GA14</h3>
    <div class="cards">
      <div class="card silver shine-6s" id="Maçon">
        <img src="../assets/aze_logo.png" alt="Entreprise de maçonnerie et gros oeuvre" style="max-width: 60%; height: auto;">
        <div style="margin-bottom: 16px;">
          <p>Entreprise de maçonnerie et gros oeuvre à Caen<br>Elle réalise des travaux de construction ou de rénovation.</p>
          <p>7 rue du Pont Rouge 14320 LAIZE LA VILLE<br><strong>06 19 76 08 21</strong> - <strong>aze2j@live.fr</strong></p>
          <%= link_to aze_path do %>
            <span class="button">visitez le site</span>
          <% end %>
        </div>
      </div>
      <div class="card silver shine-3s" id="Plombier">
        <img src="../assets/poncet.jpg" alt="plomberie et chauffage" style="max-width: 70%; height: auto;">
        <div style="margin-bottom: 16px;">
          <p>Entreprise du bâtiment spécialisée dans <br>les travaux de plomberie et chauffage.</p>
          <br>
          <p>Lieu-dit la Pépinerie 14250 TESSEL<br><strong>06 25 15 05 70</strong> - <strong>poncetemilien@hotmail.fr</strong></p>
          <%= link_to poncetsas_path do %>
            <span class="button">visitez le site</span>
          <% end %>
        </div>
      </div>
      <div class="card silver shine-6s" id="Electricien">
        <img src="../assets/lfelec.png" alt="électricité" style="max-width: 70%; height: auto;">
        <div style="margin-bottom: 16px;">
          <p>Entreprise d'électricité générale</p>
          <p>Courteil<br>14220 Le Hom<br><strong>09 52 52 15 04</strong> - <strong>06 18 24 69 96</strong><br><strong>f.lefortier@gmail.com</strong></p>
          <%= link_to lfelec_path do %>
            <span class="button">visitez le site</span>
          <% end %>
        </div>
      </div>
      <div class="card silver shine-6s" id="Carreleur">
        <img src="../assets/mattard.png" alt="carrelage Mattard" style="max-width: 70%; height: auto;">
        <div style="margin-bottom: 16px;">
          <p>Artisan carreleur dans le Calvados.</p>
          <p>Chemin Croix Saint Pierre<br>14670 SAINT-PAIR<br><strong>02 31 39 84 50</strong> - <strong>06 28 32 96 76</strong><br><strong>stephmatt.carrelage@aliceadsl.fr</strong></p>
          <%= link_to mattard_path do %>
            <span class="button">visitez le site</span>
          <% end %>
        </div>
      </div>
      <div class="card silver shine-3s" id="Couvreur">
        <img src="" alt="Couverture Charpente Terrasse Bois">
        <h5>TONY DENIAUX</h5>
        <div style="margin-bottom: 16px;">
          <p>Couverture - Charpente - Terrasse Bois<br>Bardage - Isolation<br></p>
          <p>11 impasse de la Teinture 14690 LE BÔ<br><strong>02 31 09 47 36</strong> - <strong>06 16 38 59 51</strong></p>
          <%= link_to deniaux_couverture_path do %>
            <span class="button">visitez le site</span>
          <% end %>
        </div>
      </div>
      <div class="card silver shine-3s" id="Plaquiste">
        <img src="../assets/rl_amenagement.png" alt="plaquiste" style="max-width: 60%; height: auto;">
        <div style="margin-bottom: 16px;">
          <p>Artisan plaquiste</p>
          <br>
          <p>895 rue des artisans<br>14670 TROARN<br><strong>07 81 16 93 81</strong> - <strong>a.lefrancois@rlamenagement.com</strong></p>
          <%= link_to rl_path do %>
            <span class="button">visitez le site</span>
          <% end %>
        </div>
      </div>
      <div class="card silver shine-6s" id="terrassement">
        <img src="../assets/logosam.png" alt="sam&co tp" style="width: 60%; max-width: 60%; height: auto;">
        <div style="margin-bottom: 16px;">
          <p>Terrassement, assainissement et aménagement extérieur</p>
          <br>
          <p>1 route de Maltot - RD 147<br>14320 FEUGUEROLLES BULLY<br><strong>contact@samandco-tp.com - 06 63 69 13 43</strong></p>
          <%= link_to samandco_tp_path do %>
            <span class="button">visitez le site</span>
          <% end %>
        </div>
      </div>
      <div class="card silver shine-6s" id="Peintre">
        <img src="../assets/picant.png" alt="Peinture décoration, revêtement sols et murs" style="max-width: 50%; height: auto;">
        <div style="margin-bottom: 16px;">
          <p>Peinture décoration, revêtement sols et murs<br>Ravalement - Vitrerie</p>
          <p>6 rue Camille Blaisot<br>14210 Evrecy<br><strong>02 31 80 44 00</strong> - <strong>06 82 15 04 89</strong></p>
          <%= link_to peinture_picant_path do %>
            <span class="button">visitez le site</span>
          <% end %>
        </div>
      </div>
      <div class="card silver shine-6s" id="Menuisier">
        <img src="../assets/logikinov.png" alt="menuiserie logikinov" style="max-width: 30%; height: auto;">
        <div style="margin-bottom: 16px;">
          <p>Menuisier pour la pose de Fenêtre, Porte d'entrée,<br>Porte de garage, Portail, Volet, Store<br>Pergola, Terrasse, Isolation.</p>
          <p>Allée 1 - Avenue des Digues - Zone Normandika<br>14123 FLEURY SUR ORNE<br><strong>02 31 52 00 78</strong> - <strong>benoit.briere@logikinov.com</strong></p>
          <%= link_to logikinov_path do %>
            <span class="button">visitez le site</span>
          <% end %>
        </div>
      </div>
      <div class="card silver shine-3s" id="Cheminées">
        <img src="../assets/benoist.png" alt="Cheminées Benoist" style="max-width: 50%; height: auto;">
        <div style="margin-bottom: 16px;">
          <p>Distribue et installe les plus grandes marques<br>de poêles à bois, à granulés, inserts, cheminées bois, gaz, métalliques<br>à retrouver dans 2 show-rooms :<br>14470 COURSEULLES SUR MER<br>14120 MONDEVILLE - Parking Rochebobois</p>
          <p><strong>contact@benoist.fr - 02 31 36 10 15</strong></p>
          <%= link_to benoist_path do %>
            <span class="button">visitez le site</span>
          <% end %>
        </div>
      </div>
      <div class="card silver shine-3s" id="agenceur">
        <img src="../assets/profilamenagement.png" alt="profil amenagement" style="max-width: 80%; height: auto;">
        <div style="margin-bottom: 16px;">
          <p>Menuiserie & Agencement sur mesure</p>
          <p>Cuisine - Dressing - Bureau ... pour particuliers & professionels<br>Aménagement de véhicules et remorques<br>pour Foodtruck & Loisir</p>
          <br>
          <p>ZA des Cerisiers 14210 EVRECY<br><strong>02 31 28 06 00</strong> - <strong>06 60 87 18 16</strong><br><strong>profil@profil-amenagement.com</strong></p>
          <%= link_to profil_amenagement_path do %>
            <span class="button">visitez le site</span>
          <% end %>
        </div>
      </div>
      <div class="card silver shine-3s" id="chauffage">
        <img src="../assets/nc.png" alt="normandie chauffage" style="width: 60%; max-width: 80%; height: auto;">
        <div style="margin-bottom: 16px;">
          <p>Artisan chauffagiste<br>Pompe à chaleur, Poêle et chaudières à granulés, fioul, gaz</p>
          <br>
          <p>491 rue des Artisans<br>14670 TROARN<br><strong>julien.nc14@gmail.com - 06 74 96 37 00</strong></p>
          <%= link_to normandie_chauffage_path do %>
            <span class="button">visitez le site</span>
          <% end %>
        </div>
      </div>
      <div class="card-ga14">
        <img src="../assets/logo.png" alt="Groupement des artisans du Calvados" style="max-width: 80%; height: auto;">
        <div style="margin-bottom: 16px;">
          <h5>Des travaux ? Un projet ?</h5>
          <p>N'hésitez pas à contacter <br>nos artisans</p>
          <img src="../assets/contact-button.png" data-toggle="modal" data-target="#exampleModal" id="img-contact-house" class="flashit">
        </div>
      </div>
    </div>
    <div class="label d-none" id="js-animation">
      <h3>Vos travaux en toute confiance et en toute sécurité</h3>
      <div class="labels">
        <img src="../assets/qualibat.png" alt="qualibat rge">
        <img src="../assets/labelartisan.jpg" alt="label artisan rge">
        <img src="../assets/qualibois.png" alt="qualibois rge">
        <img src="../assets/logo.png" alt="GA14 artisans du Calvados">
      </div>
    </div>
  </div>
</div>

app/views/pages/lfelec.html.erb
<div class="pageforeach">
  <img id="logo" src="../assets/lfelec.png" alt="" >
  <br>
  <h1>Entreprise du bâtiment spécialisée dans l'électricité générale.</h1><br>
  <h3>coordonnées</h3>
  <p>Courteil<br>14220 Le Hom</p>
  <p style="font-weight: bolder;">09 52 52 15 04 - 06 18 24 69 96 - f.lefortier@gmail.com</p>
  <h2>Interventions</h2>
  <div class="domaines">
    <div class="domaine">
      <h5>Electricité</h5>
    </div>
<!--     <div class="domaine">
      <h5>Chauffage</h5>
    </div>
    <div class="domaine">
      <h5>Salle de Bain</h5>
    </div> -->
  </div>
  <br>
  <h2>Mes dernières réalisations</h2>
  <br>
  <h3>Retrouvez prochainement mes dernières réalisations</h3>
<!--   <h3>Rénovation d'une salle de bain</h3>
  <div class="domaines">
    <img src="../assets/avant1.jpg" alt="">
    <img src="../assets/avant2.jpg" alt="">
    <img src="../assets/apres2.jpg" alt="">
    <img src="../assets/apres1.jpg" alt="">
  </div>
  <h3>Aménagement d'un petit espace</h3>
  <div class="domaines">
    <img src="../assets/petitespace1.jpg" alt="">
    <img src="../assets/petitespace2.jpg" alt="">
  </div>
  <h3>Salle de bain</h3>
  <div class="domaines">
    <img src="../assets/sdb1.jpg" alt="">
    <img src="../assets/sdb2.jpg" alt="">
    <img src="../assets/sdb3.jpg" alt="">
  </div> -->
</div>

app/views/pages/logikinov.html.erb
<div class="pageforeach">
  <img id="logo" style="width: 20%;" src="../assets/logikinov.png" alt="" >
  <br>
  <h1>Entreprise du bâtiment spécialisée dans la menuiserie<br>pour la pose de Fenêtre, Porte d'entrée,<br>Porte de garage, Portail, Volet, Store<br>Pergola, Terrasse, Isolation.</h1><br>
  <div style="display: flex;">
    <a href="https://www.logikinov.com/" class="button">visitez le site</a>
  </div>
  <h3>coordonnées</h3>
  <p>Allée 1 - Avenue des Digues - Zone Normandika<br>14123 FLEURY SUR ORNE</p>
  <p style="font-weight: bolder;">02 31 52 00 78 - benoit.briere@logikinov.com</p>
  <h2>Interventions</h2>
  <div class="domaines">
    <div class="domaine">
      <h5>Fenêtres</h5>
    </div>
    <div class="domaine">
      <h5>Portes</h5>
    </div>
    <div class="domaine">
      <h5>Store & volet</h5>
    </div>
  </div>
  <br>
  <h2>Nos dernières réalisations</h2>
  <br>
  <h3>Pose de fênetres</h3>
  <div class="domaines">
    <img src="../assets/fenetre1.png" style="width: 120%; margin-right: 16px;" alt="">
  </div>
  <h3>Installation d'un portail</h3>
  <div class="domaines">
    <img src="../assets/portail1.png" alt="">
  </div>
  <h3>Pose d'une pergola bioclimatique avec une paroi en verre</h3>
  <div class="domaines">
    <img src="../assets/pergola1.png" alt="">
    <img src="../assets/pergola2.png" alt="">
    <img src="../assets/pergola3.png" alt="">
  </div>
</div>

app/views/pages/mention.html.erb
<div class="pageforeach">
  <h3>Mentions légales</h3>
  <br>
  <br>
  <p>Nom de la personne moral, immatriculation,</p>
  <p>Coordonnées</p>
  <p>Enregistrée sous le n° SIRET XXX XXX XXX 000XX Directeur de la publication : Nom Prénom</p>
  <br>
  <p>Editeur, conceptions graphique et technique, développement du site internet, ci-après :</p>
  <p>Emmanuel ROSE</p>
  <p>14 place de l'Hôtel de ville 92600 Asnières sur Seine</p>
  <p>Auto-entrepreuneur enregistré au Registre du Commerce et des Sociétés de Nanterre sous le numéro 893 088 559</p>
  <p>Email : emrose351@gmail.com - Téléphone : 0659777183</p>
  <br>
  <p>Hébergement du site internet, ci-après la société : </p>
  <p>Heroku (Salesforce - The Landmark @ 1 Market St. Suite 300 - San Francisco, CA 94105)</p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<nav role="navigation" style='height: 0.5px;'>
  <div id="menuToggle">
    <!--
    A fake / hidden checkbox is used as click reciever,
    so you can use the :checked selector on it.
    -->
    <input type="checkbox" />

    <!--
    Some spans to act as a hamburger.

    They are acting like a real hamburger,
    not that McDonalds stuff.
    -->
    <span></span>
    <span></span>
    <span></span>

    <!--
    Too bad the menu has to be inside of the button
    but hey, it's pure CSS magic.
    -->
    <ul id="menu">
<!--       <a href="#"><li>Home</li></a>
      <a href="#"><li>About</li></a>
      <a href="#"><li>Info</li></a>
      <a href="#"><li>Contact</li></a>
      <a href="https://erikterwan.com/" target="_blank"><li>Show me more</li></a> -->
      <img src="../assets/contact-button.png" data-toggle="modal" data-target="#exampleModal">
      <%= link_to "Agenceur", profil_amenagement_path%>
      <%= link_to "Aménagement Ext.", samandco_tp_path%>
      <%= link_to "Carreleur", mattard_path%>
      <%= link_to "Chauffagiste", normandie_chauffage_path%>
      <%= link_to "Cheminées", benoist_path%>
      <%= link_to "Couvreur", deniaux_couverture_path%>
      <%= link_to "Electricien", lfelec_path%>
      <%= link_to "Maçon", aze_path%>
      <%= link_to "Menuisier", logikinov_path%>
      <%= link_to "Peintre", peinture_picant_path%>
      <%= link_to "Plaquiste", rl_path%>
      <%= link_to "Plombier", poncetsas_path%>

    </ul>
  </div>
</nav>